process_input:
  description: >
    Analyze the user's input and classify its intent.
    
    REQUIRED OUTPUT:
    1. intent_classification: One of "market_research", "business_knowledge", or "legal"
    2. refined_question: A clear, concise version of the original question
    3. intent_confidence_percentage: Numerical confidence score (0-100)
    4. clarification_request_if_needed: Any needed clarification
