web_scraping_task:
  description: >
    Scrape and extract the complete content from the following URL:
    
    ===URL===
    {url}
    ===URL===

    Focus on identifying content relevant content, by removing all content that is not part of the article.
    DO NOT interpret the content
    DO NOT sumnmarize the content
    DO NOT shorten or modify in any form or fashion
    DO NOT include any ads, navigation, links, comments, or other irrelevant content
    DO NOT include any images or videos
    ALWAYS return the whole content of the article from the parsed web page

  expected_output: >
    A structured document in markdown format containing:
    - Metadata annotations - only source URL and publication date, if available.
    - The complete content of the website cleaned from irrelevant data such as: ads, navigation, comments, etc.